version: '3'
services:
  postgres:
    build: postgres/
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=orgdb
    ports:
      - "5432:5432"
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - "postgres:db-data"
volumes:
  db-data: {}
